site_name: Render Engine

nav:
    - Home: index.md
    - Getting Started: quickstart.md
    - Page: page.md
    - Collection: collection.md
    - Site: site.md
    - Engine: engine.md

theme: readthedocs
