[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "render_engine"
version = "2022.9.1"
description = "A Flexible Static Site Generator for Python"
readme = "README.md"

dependencies = [
    "Jinja2",
    "markdown2",
    "pendulum",
    "more-itertools",
    "python-frontmatter",
    "python-slugify",
    "rich",
]

[project.optional-dependencies]
docs = ["mkdocs", "mkdocs-material"]
dev = ["pytest", "pytest-cov", "tox"]

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = "-ra --cov"
testpaths = [
    "tests"
]
pythonpath = ['src']

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = python3.9,python3.10
isolated_build = True

[testenv]
deps =
    pytest
    pytest-cov
    pytest-mock
commands = pytest --cov src/render_engine tests

[tox:.package]
basepython = python3
"""
