[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "render_engine"
version = "2022.9.1"
description = "Static Site Generator with a Flask-like flair"
authors = ["Jay Miller <kjaymiller@gmail.com>"]
readme = "README.md"
requires = ">=3.9"
license = {text = "MIT License"}
dependencies = [
    "Jinja2",
    "markdown2",
    "pendulum",
    "more-itertools",
    "python-slugify",
    "python-frontmatter",
    "rich",
    ]
classifiers = [
    "Programming Language :: Python :: 3",
]



[project.optional-dependencies]
dev=[
    "pytest",
    "pytest-cov",
    "pytest-mock",
    "perflint",
    "pre-commit",
    "tox"
    ]
docs=["Sphinx", "sphinx-rtd-theme"]


[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = "-ra --cov"
testpaths = [
    "tests"
]
pythonpath = ['src']

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = python3.9,python3.10
isolated_build = True

[testenv]
deps =
    pytest
    pytest-cov
    pytest-mock
commands = pytest --cov src/render_engine tests

[tox:.package]
basepython = python3
"""
