# Config Contents
# This is an example config.yaml file. It is filled completely but ALL values are optional
# In testing, not all values work
# lowercase values indicate a class settings value
# UPPERCASE values indicate an environment template variable
#
base_page_information:
   timezone: 'US/Pacific' # Time Zone for date_published\date_modified Standard or GMT+ to indicate timezone Default: GMT
   timedate_format: 'iso2822' # for date_published\date_modified use iso, rfc, or custom 'Y M D H M S' format
   page_defaults:
     PAGE_TITLE: Yes # Bool - Page.title
     PAGE_URL: Yes # Bool - Page.url
     PAGE_AUTHOR: Yes # Bool - Page.author.name
     PAGE_AUTHOR_EMAIL: Yes # Bool - Page.author.email
     PAGE_AUTHOR_SITE:  Yes # Bool - Page.author.site
     PAGE_AUTHOR_SOCIAL: Yes # Bool - creates all the types below
    # If Social is Yes all of these values will be set to Yes by default only populated fields are added
     PAGE_AUTHOR_TWITTER: Yes # Bool - Page.author.social
     PAGE_AUTHOR_FACEBOOK: Yes # Bool - Page.author.social.facebook
     PAGE_AUTHOR_LINKEDIN: Yes # Bool - Page.author.social.linkedin
     PAGE_AUTHOR_MICROBLOG: Yes # Bool - Page.author.social.microblog
     PAGE_AUTHOR_TUMBLR: Yes # Bool - Page.author.social.tumblr
     PAGE_AUTHOR_REDDIT: Yes # Bool - Page.author.social.reddit

base_collection_information:
   default_feeds: No # Bool - Default No - always creates rss/json feeds for collections
   archive: No # Bool - Default No - always creates an archive page for collections
   date_archiving: No # Bool - Default No - create date based archive pages
   pagination: No # Bool - Default No - archives are paginated (default 10 per page) paginate archives
   collection-default-slug: filename # **Default**: filename, **Options**: filename/datetime/custom 'Y M D H M S' )

engine_collection_information:
  relative urls: No # Bool - Default No - Use relative urls instead of absolute urls only works if SITE_URL is defined
  overwrite: No # Bool - Default: No - always overwrite files
  environment_global_variables:
    SITE_URL: https://example.com
    SITE_NAME: Example Web Site
    SITE_DESCRIPTION: A demo site using Render Engine
    SITE_AUTHOR: Yes # Bool - Engine.author.name - if exists, site_AUTHOR will often be used as the default PAGE_AUTHOR
    SITE_AUTHOR_EMAIL: Yes # Bool - Engine.author.email
    SITE_AUTHOR_SITE:  Yes # Bool - Engine.author.site
    SITE_AUTHOR_SOCIAL: Yes # Bool - creates all the types below
    # If Social is Yes all of these values will be set to Yes by default only populated fields are added
    SITE_AUTHOR_TWITTER: Yes # Bool - Engine.author.social
    SITE_AUTHOR_FACEBOOK: Yes # Bool - Engine.author.social.facebook
    SITE_AUTHOR_LINKEDIN: Yes # Bool - Engine.author.social.linkedin
    SITE_AUTHOR_MICROBLOG: Yes # Bool - Engine.author.social.microblog
    SITE_AUTHOR_TUMBLR: Yes # Bool - Engine.author.social.tumblr
    SITE_AUTHOR_REDDIT: Yes # Bool - Engine.author.social.reddit

