site_name: Render Engine
site_url: https://render-engine.readthedocs.io
theme:
  name: material
nav:
  - Home: index.md
  - Getting Started:
    - getting-started/installation.md
    - getting-started/create-app.md
    - getting-started/layout.md
    - getting-started/creating-a-page.md
    - getting-started/creating-a-collection.md
  - Components:
    - Page: page.md
    - Collection:
      - Collection: collection.md
      - Archive: archive.md
    - Site: site.md
markdown_extensions:
  toc:
    permalink: True
  codehilite:
    guess_lang: False
  admonition:
  pymdownx.details:
  pymdownx.superfences:
watch:
  - ../src/render_engine
plugins:
- search
- autorefs
- mkdocstrings:
    handlers:
      python:
        options:
          show_source: false
