site_name: Render Engine
site_url: https://render-engine.readthedocs.io
theme:
  name: material
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Objects:
    - Page: page.md
    - Collection: collection.md
    - Site: site.md
markdown_extensions:
  toc:
    permalink: True
  codehilite:
    guess_lang: False
