name: Format and Lint with Ruff
on: 
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      # Update output format to enable automatic inline annotations.
      - name: Run Ruff
        run: |
            ruff check --fix --output-format=github src
            ruff format src
      - name: Commit changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.name "Ruff"
            git config --global user.email "ruff-action@users.noreply.github.com"
            git add -A
            git commit -m "Format and lint with Ruff"
            git push 
          fi
          
      
        
