name: PyTest
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-against-matrix:
    runs-on: ubuntu-latest
    if: ${{github.event_name == 'workflow_call'}} || ${{github.event_name == 'workflow_dispatch'}}
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install requirements
        run: |
          python -m pip install -e .[dev]
      - name: Run tests
        run: |
          python -m pytest


  test-against-latest:
    runs-on: ubuntu-latest
    if: ${{github.event_name == 'pull_request'}} || ${{github.event_name == 'push'}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install requirements
        run: |
          python -m pip install -e .[dev]
      - name: Run tests
        run: |
          python -m pytest
