name: PyTest
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-with-pytest:
    runs-on: ubuntu-latest

    container:
      image: .devcontainer/Dockerfile
      options: --IMAGE python:3.11
    
    steps:
      - uses: actions/checkout@v3
      - name: Install requirements
        run: |
          bash .devcontainer/setup.sh

      - name: Run tests
        run: python -m pytest
