name: Test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-with-pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install requirements
        run: pip install requirements.txt
      
      - name: Install tests
        run: pip install pytest pytest-mock pytest-cov

      - name: Run tests
        run: python -m pytest
